org: ${env:SLS_ORG}
service: qubo-classroom-api

provider:
  name: aws
  runtime: python3.9
  iam:
    role: ${env:AWS_ROLE_ARN}
  memorySize: 1024
  timeout: 29
  environment:
    SERVICE_NAME: qubo-classroom-api
    STAGE: ${sls:stage}
    TABLE_CLASSROOMS: ${sls:stage}-qubo-classroom-table
    TABLE_USERS: ${sls:stage}-qubo-auth-user-table # Added this line
    TABLE_SESSIONS: ${sls:stage}-qubo-sessions-table
    TABLE_GAME_SESSIONS: ${sls:stage}-qubo-game-sessions
    VALIDATE_TOKEN_FUNCTION: validateToken
    USER_SERVICE_NAME: qubo-auth-api

functions:
  createClassroom:
    handler: createClassroom.lambda_handler
    events:
      - http:
          path: classrooms/create
          method: post
          cors: true

  getClassroomsByTeacherId:
    handler: getClassroomsByTeacherId.lambda_handler
    events:
      - http:
          path: classrooms/teacher
          method: get
          cors: true

  getStudentsByClassroom:
    handler: getStudentsByClassroom.lambda_handler
    events:
      - http:
          path: classrooms/{classroom_id}/students
          method: get
          cors: true

  getClassroomStats:
    handler: getClassroomStats.lambda_handler
    events:
      - http:
          path: classroom/stats/{classroom_id}
          method: get
          cors: true

resources:
  Resources:
    ClassroomTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_CLASSROOMS}
        AttributeDefinitions:
          - AttributeName: classroom_id
            AttributeType: S
          - AttributeName: teacher_id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: classroom_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: teacher-name-index
            KeySchema:
              - AttributeName: teacher_id
                KeyType: HASH
              - AttributeName: name
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
