org: ${env:SLS_ORG}
service: qubo-classroom-api

provider:
  name: aws
  runtime: python3.9
  iam:
    role: ${env:AWS_ROLE_ARN}
  memorySize: 1024
  timeout: 29
  environment:
    SERVICE_NAME: qubo-classroom-api
    STAGE: ${sls:stage}
    TABLE_CLASSROOMS: ${sls:stage}-classroom-table
    VALIDATE_TOKEN_FUNCTION: validateToken

functions:
  createClassroom:
    handler: createClassroom.lambda_handler
    events:
      - http:
          path: classrooms/create
          method: post
          cors: true

resources:
  Resources:
    ClassroomTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_CLASSROOMS}
        AttributeDefinitions:
          - AttributeName: classroom_id
            AttributeType: S
        KeySchema:
          - AttributeName: classroom_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true