org: ${env:SLS_ORG}
service: qubo-ia-api

provider:
  name: aws
  runtime: python3.9
  memorySize: 1024
  timeout: 30
  environment:
    USER_SERVICE_NAME: qubo-auth-api
    STAGE: ${sls:stage}
    GITHUB_TOKEN: ${env:GITHUB_TOKEN}
    VALIDATE_TOKEN_FUNCTION: validateToken

functions:
  generateExercises:
    handler: generateExercises.lambda_handler
    events:
      - http:
          path: ia/generate-exercises
          method: post
          cors: true
